<?php

namespace MYPS\Amio\Api;

use Psr\Http\Message\ResponseInterface;

/**
 * Class Client
 */
final class Client
{
    const BASE_URL = 'https://api.amio.io/';

    /**
     * Guzzle http client
     *
     * @var \GuzzleHttp\Client
     */
    private $_client;


    /**
     * Client constructor
     *
     * @param string $accessToken Access token generated by Amio.io.
     */
    public function __construct(string $accessToken)
    {
        $this->_client = new \GuzzleHttp\Client(
            [
                'base_uri' => self::BASE_URL,
                'headers' => [
                    'Content-Type' => 'application/json',
                    'Authorization' => 'Bearer ' . $accessToken,
                ],
            ]
        );

    }//end __construct()


    /**
     * Create request to Amio.io
     *
     * @param string $method Request method.
     * @param string $uri Request uri.
     * @param array $options Request additional options.
     *
     * @return ResponseInterface
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function request(string $method, string $uri, array $options = []): ResponseInterface
    {
        return $this->_client->request($method, $uri, $options);

    }//end request()


}//end class
